apiVersion: v1
kind: Service
metadata:
  name: fixmate-backend
  namespace: fixmate
  labels:
    app: fixmate-backend
spec:
  type: LoadBalancer
  selector:
    app: fixmate-backend
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
