apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: fixmate
type: Opaque
data:
  DB_USERNAME: Zml4bWF0ZQ==
  DB_PASSWORD: Zml4bWF0ZQ==
  JWT_SECRET: YTJGcWMyUm1hR3RxWVhOb1pHWnFhMkZvYzJSbWFHcGthR0ZxYTJSbWFHbz0=
